USE Z_UNIVER;
select * from
TEACHER full join PULPIT on
TEACHER.PULPIT = PULPIT.PULPIT

select * from
PULPIT full join TEACHER on
TEACHER.PULPIT = PULPIT.PULPIT

select PULPIT.FACULTY , PULPIT.PULPIT, PULPIT.PULPIT_NAME from
PULPIT full join TEACHER on
TEACHER.PULPIT = PULPIT.PULPIT

select TEACHER.GENDER, TEACHER.PULPIT, TEACHER.TEACHER, TEACHER.TEACHER_NAME from
PULPIT full join TEACHER on
TEACHER.PULPIT = PULPIT.PULPIT

