Use Z_UNIVER;
select AUDITORIUM , AUDITORIUM.AUDITORIUM_TYPE, AUDITORIUM_CAPACITY, AUDITORIUM_NAME, AUDITORIUM_TYPENAME 
from AUDITORIUM join AUDITORIUM_TYPE
			on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
select AUDITORIUM , AUDITORIUM.AUDITORIUM_TYPE, AUDITORIUM_CAPACITY, AUDITORIUM_NAME, AUDITORIUM_TYPENAME 
from AUDITORIUM join AUDITORIUM_TYPE
			on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE and AUDITORIUM_TYPENAME like '%компьютер%'
 select a1.AUDITORIUM , a1.AUDITORIUM_TYPE, a1.AUDITORIUM_CAPACITY, a1.AUDITORIUM_NAME, a2.AUDITORIUM_TYPENAME 
 from AUDITORIUM a1, AUDITORIUM_TYPE a2
			where a1.AUDITORIUM_TYPE = a2.AUDITORIUM_TYPE
select a1.AUDITORIUM , a1.AUDITORIUM_TYPE, a1.AUDITORIUM_CAPACITY, a1.AUDITORIUM_NAME, a2.AUDITORIUM_TYPENAME 
from AUDITORIUM a1, AUDITORIUM_TYPE a2
			where a1.AUDITORIUM_TYPE = a2.AUDITORIUM_TYPE and a2.AUDITORIUM_TYPENAME like '%компьютер%'