USE Z_UNIVER;

Select FACULTY.FACULTY_NAME , PULPIT.PULPIT_NAME From FACULTY, PULPIT 
Where PULPIT.FACULTY = FACULTY.FACULTY and 
FACULTY.FACULTY In (Select FACULTY From PROFESSION 
Where PROFESSION_NAME Like '%òåõíîëîãè%') 

SELECT PULPIT.PULPIT_NAME, FACULTY.FACULTY 
FROM FACULTY JOIN PULPIT 
ON FACULTY.FACULTY = PULPIT.FACULTY 
Where FACULTY.FACULTY In 
(Select FACULTY From PROFESSION Where PROFESSION_NAME Like '%òåõíîëîãè%') 

Select DISTINCT F.FACULTY_NAME, P.PULPIT_NAME 
FROM FACULTY F JOIN PROFESSION PR 
On PR.FACULTY=F.FACULTY 
JOIN PULPIT P On F.FACULTY=P.FACULTY 
WHERE PROFESSION_NAME LIKE '%òåõíîëîãè%' 

SELECT AUDITORIUM.* 
FROM AUDITORIUM 
where AUDITORIUM_CAPACITY = ( 
select top (1) AUDITORIUM_CAPACITY 
FROM AUDITORIUM A 
where AUDITORIUM.AUDITORIUM_TYPE = A.AUDITORIUM_TYPE
Order by AUDITORIUM_CAPACITY desc 
)

SELECT FACULTY_NAME 
FROM FACULTY 
where not exists (select * from PULPIT where FACULTY.FACULTY = PULPIT.FACULTY) 


SELECT top 1 
(select avg(PROGRESS.NOTE) FROM PROGRESS 
where PROGRESS.SUBJECT like 'ÎÀèÏ') ÎÀÈÏ, 
(select avg(PROGRESS.NOTE) FROM PROGRESS 
where PROGRESS.SUBJECT like 'ÊÃ') ÊÃ, 
(select avg(PROGRESS.NOTE) FROM PROGRESS 
where PROGRESS.SUBJECT like 'ÑÓÁÄ') ÑÓÁÄ 

SELECT PROGRESS.NOTE, PROGRESS.IDSTUDENT FROM PROGRESS 
WHERE PROGRESS.NOTE >=all (select PROGRESS.NOTE FROM PROGRESS where PROGRESS.SUBJECT like 'Ê%') 

SELECT PROGRESS.NOTE, PROGRESS.IDSTUDENT FROM PROGRESS 
WHERE PROGRESS.NOTE >=any (select PROGRESS.NOTE FROM PROGRESS where PROGRESS.SUBJECT like 'Ê%')

SELECT STUDENT.BDAY,STUDENT.NAME FROM STUDENT 
WHERE STUDENT.BDAY IN(SELECT STUDENT.BDAY FROM STUDENT GROUP BY STUDENT.BDAY
HAVING COUNT(*) > 1)
order by STUDENT.BDAY;